name: CI/CD Pipeline
run-name: ${{github.actor}} CI/CD Pipeline on ${{github.ref_name}}
on:
  push:
    branches:
      - "main"
      - "develop"
      - "feature/*"
      - "bugfix/*"
      - "hotfix/*"
      - "release/*"
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, unlabeled, labeled]
    branches-ignore:
      - " ga-ignore-"

jobs:
  size:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Check the size of the repository
        run: |
          SIZE=$(du -skh --exclude=.git | cut -f1)
          echo "The size of the repository is $SIZE"
          if [ $SIZE -gt 30000 ]; then
            echo "Size of the repository is too big"
            exit 1
          fi

  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm i --legacy-peer-deps

      - name: Run tests
        run: npm run test:ci

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  push_to_mirror:
    runs-on: self-hosted
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ vars.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
